### ISSUE TITLE
Coffeescript indentation conflict

### ISSUE THREAD

**Issue by nunziofiore** [marchenko1985/sublime-reindent-on-save#2]
Hi
 it seems that we have some problem with coffeescript, how did you solve it?
Nunzio

**Comment by nunziofiore** [comment]
and yml too seems to have a problem

**Comment by nunziofiore** [comment]
perhaps there's a way to say: use autosave indent only for
js
html
ruby
?

**Comment by marchenko1985** [comment]
Yep, it seems to be the best solution

**Comment by nunziofiore** [comment]
and how we can catch it? :)

**Comment by marchenko1985** [comment]
Released 1.1.0 version with ability to specify file types to reindent on save.

Try to update plugin, and add

```
"reindent_on_save": ["js", "html", "rb"]
```

to your settings, and you are done.

**Comment by nunziofiore** [comment]
great, I'll find where I have to put this line and in this way I can continue to use that saving life wonderful plugin

**Comment by marchenko1985** [comment]
Probably I will add some generic description on how to do this into plugin description

**Comment by nunziofiore** [comment]
Great

Il giovedì 26 giugno 2014, Marchenko Alexandr notifications@github.com ha
scritto:

> Probably I will add some generic description on how to do this into plugin
> description
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mac2000/sublime-reindent-on-save/issues/2#issuecomment-47193935
> .

## 

Sent from Gmail Mobile

**Comment by marchenko1985** [comment]
Here is how you would add options to Sublime:

https://github.com/mac2000/sublime-reindent-on-save/blob/master/README.md#how-to-add-configuration-option

**Comment by nunziofiore** [comment]
perfect work, thank you
add also that you need to restart sublime after settings change, in this way it will be perfect
