### ISSUE TITLE
How to fix redo / undo?

### ISSUE THREAD

**Issue by interpegasus** [marchenko1985/sublime-reindent-on-save#4]
After installing sublime-reindent-on-save and auto-save, the redo-undo functionality mostly says:
- undo reindent
- redo reindent

I would like to know how to ignore the reindent command, in the 'undo' and 'redo' commands, in sublime text? 

Thanks

**Comment by marchenko1985** [comment]
Reindent is buildin Sublime command so there is no way to control that outside.

What I mean: You may try to press `Ctrl+A` then `Ctrl+P` type `Reindent` and press `Enter` (actually plugin just make this every time you save your file) after performing this actions reindent will be in undo

Hope that helps

**Comment by interpegasus** [comment]
Thanks for the tips. Modifying the auto-save frequency allows enough time for redo undo  functionality to work as expected. Cheers!

**Comment by marchenko1985** [comment]
Oh I see now what you are fighting with, may be the best option will be to auto save on focus lost only e.g. you made change, switch to browser, editor loose focus and save changes
