### ISSUE TITLE
comments line with single-line // 

### ISSUE THREAD

**Issue by ebnibrahem** [marchenko1985/sublime-reindent-on-save#8]
When i type code like in php file :

class App{
//plugin do not reindent this line
/*But when comment like this  plugin did  reindent this line*/
}

**Comment by marchenko1985** [comment]
Plugin itself does not do nothing fancy, all it does - is just calling build in sublimes reindent, what I am trying to say that even if you delete this plugin, and try sublimes reindent behavior will be the same. Just try it out, and if it is so, feel free to close this issue
